server:
  port: 8080

spring:
  application:
    name: InkHub-backend

  servlet:
    multipart:
      max-file-size: 20MB        # 单文件最大 5MB
      max-request-size: 20MB

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/inkhub?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 050608 # 环境变量提供（本地 IDEA 运行配置里填 050608，不提交 GitHub）
    hikari:
      maximum-pool-size: 10

  data:
      redis:
        host: localhost
        port: 6379
        database: 0             # 默认 0 号库
        password:               # 没设密码就留空
        timeout: 5s
        lettuce:
          pool:
            max-active: 8       # 最大连接数
            max-idle: 8
            min-idle: 0

  jackson:
      date-format: yyyy-MM-dd HH:mm:ss
      time-zone: GMT+8

jwt:
  secret: NcIhLoXWXvO+Uh0KTn0nmjwitdG94LpvRc1ErlcdRtYlTW/x0ysne/qy2wWLcfku # 环境变量提供（本地 IDEA 运行配置里填原值，不提交 GitHub）
  expire: 7200000


mybatis-plus:

  mapper-locations: classpath:mapper/*.xml
  # 实体类包路径（@TableName 的实体）
  type-aliases-package: com.InkHub_backend.entity
  configuration:
    map-underscore-to-camel-case: true   # 下划线自动转驼峰：user_id → userId
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl   # 控制台打印 SQL（调试用）
  global-config:
    banner: false              # 关掉启动时的 MP logo
    db-config:
      id-type: auto            # 主键自增
      logic-delete-field: deleted        # 逻辑删除字段名（表里有才配）
      logic-delete-value: 1              # 删除值
      logic-not-delete-value: 0

springdoc:
  api-docs:
    enabled: true                    # 是否生成文档（生产环境改 false）
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
  packages-to-scan: com.example.InkHub_backend.controller   # 只扫描 controller

# 上传文件保存目录（部署 Docker 时挂载卷到这个目录）
upload:
  dir: ./uploads